name: pet_adote
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: ^3.6.0
dependencies: 
  flutter:
    sdk: flutter 
  flutter_localizations: 
    sdk: flutter
  flutter_svg: ^2.0.12
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.3
  connectivity_plus: ^6.1.0
  web: any
  universal_html: ^2.2.4
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.1
  image_picker: ^1.2.0
  url_launcher: ^6.3.1
  mailer: ^6.5.0
  mailto: ^2.0.0
  http: ^1.5.0
  emailjs: ^4.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter   
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Leckerli One
      fonts: 
        - asset: assets/fonts/LeckerliOneRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterMedium.ttf
          weight: 500