name: Flutter Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: flutter setup
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          cache: true

      - name: dependencies - install
        run: flutter pub get

      - name: flutter analyze
        run: flutter analyze

      - name: build apk
        run: flutter build apk --release

      - name: APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
